### PR TITLE
Add card name when creating a token

### PR DESCRIPTION
**Pull request by morrislaptop**

### CODE REVIEW

**Comment by JacobBennett** [comment]
Can you help me understand why this is needed or what this is fixing? Is this now a required field? Or is it just in your case that it is helpful to have a name associated with the token?

**Comment by morrislaptop** [comment]
Helpful :)

**Comment by morrislaptop** [comment]
Close or merge?

**Comment by morrislaptop** [comment]
Merging?

**Comment by morrislaptop** [comment]
👊 bump

**Comment by JacobBennett** [comment]
merged :)

**Comment by morrislaptop** [comment]
And release? :) @JacobBennett

**Comment by morrislaptop** [comment]
👊 bump

**Comment by JacobBennett** [comment]
released :) 

https://github.com/JacobBennett/StripeTestToken/releases/tag/v1.0.2

**Pull request merged**
